### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json

{
"title": "Molor sit amet2",
"date": "2021-01-01T12:00:00Z",
"description": "Lorem ipsum",
"priority": "normal",
"status": "todo"
}

### Update a task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
    "id": "ac31cc0f-babc-4368-9962-94bffba238c5",
    "status": "inProgress"
}